CREATE DATABASE TestDB;
DROP TABLE IF EXISTS `Sag_test`;
CREATE TABLE `Sag_test` (
snapnum SMALLINT NOT NULL,
redshift FLOAT NOT NULL,
NInFile BIGINT NOT NULL,
fileNum INTEGER NOT NULL,
phkey BIGINT NULL, 
GalaxyID BIGINT NOT NULL,
HostHaloID BIGINT NOT NULL,
HaloMass DOUBLE NOT NULL,
MZstarDisk DOUBLE NOT NULL,
MagStarSDSSg DOUBLE  NOT NULL,
x FLOAT NOT NULL,
y FLOAT NOT NULL,
z FLOAT NOT NULL
) ENGINE=MyISAM;
